# See http://www.appveyor.com/docs/appveyor-yml for many more options

environment:
  gallery:
    secure: p48jnOjtyEeyHlIOWwS64Mrnjiq2f3YUDpBDE7woUNCV+z5JVzqB0DhEtCCTQagZ

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

build: false

#Kick off the CI/CD pipeline
test_script:
- ps: . .\Helper.Build.ps1